/**
 * /limitations — User-facing limitations page
 *
 * Rule R19c: "Create user-facing limitations page."
 * Rule R19d: "Mirror principle — the system must reflect its own limitations honestly."
 *
 * This page exists because the Ethical Analysis (R17-R20 source document) states:
 * "Honest positioning is not optional." Users deserve to know what this tool
 * cannot do before they rely on it.
 */

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Limitations — SageReasoning',
  description: 'What SageReasoning can and cannot do. Honest disclosure of our limitations.',
}

export default function LimitationsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 font-body text-sage-800">

      <div className="mb-10">
        <h1 className="font-display text-3xl font-medium text-sage-900 mb-2">
          What SageReasoning Cannot Do
        </h1>
        <p className="text-sage-600 text-sm">
          Honest disclosure of our limitations, because the Stoics taught that
          self-knowledge begins with knowing what you do not know.
        </p>
      </div>

      <section className="space-y-8 leading-relaxed">

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            We are not therapists
          </h2>
          <p>
            SageReasoning provides philosophical perspectives based on Stoic virtue ethics.
            It is not a mental health service, counselling tool, or therapeutic intervention.
            If you are experiencing psychological distress, please contact a qualified
            mental health professional or crisis service. Our tool cannot and should not
            replace that support.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            AI-generated reasoning has limits
          </h2>
          <p>
            Every evaluation produced by SageReasoning is generated by an AI language model
            (Anthropic&rsquo;s Claude). AI models can produce outputs that are plausible-sounding
            but incorrect, miss important context, or reflect biases in their training data.
            Our evaluations should be treated as one perspective to consider, not as
            authoritative judgements about your character or decisions.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            Stoicism is one philosophical tradition among many
          </h2>
          <p>
            Our reasoning framework is grounded in ancient Stoic philosophy. While we believe
            this tradition offers valuable insights, it is one ethical framework among many.
            SageReasoning does not claim that Stoic reasoning is universally correct, superior
            to other ethical traditions, or applicable to every situation. Other philosophical
            traditions (virtue ethics, deontology, consequentialism, care ethics, Ubuntu,
            Buddhist ethics, and many others) offer legitimate and valuable perspectives
            that our framework does not capture.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            We cannot assess your full situation
          </h2>
          <p>
            When you submit an action or decision for evaluation, you provide a text description.
            That description is necessarily incomplete. We cannot know your full emotional state,
            your relationships, your cultural context, your physical health, your financial
            situation, or the thousand other factors that shape a real human decision.
            Our evaluations work with what you tell us, which is always a simplification
            of reality.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            Passion diagnosis is not clinical diagnosis
          </h2>
          <p>
            Our Stoic passion taxonomy identifies patterns in reasoning that ancient Stoics
            called &ldquo;passions&rdquo; (false judgements about what is good or bad). This is a
            philosophical framework for self-examination, not a psychological or clinical
            assessment. Identifying a &ldquo;passion&rdquo; in your reasoning does not mean you have
            a psychological disorder. If you find that our passion diagnoses are causing
            distress rather than insight, please stop using the tool and consider speaking
            with a professional.
          </p>
          <p className="mt-3 text-sage-600 text-sm italic">
            Rule R20d: We specifically discourage applying the passion taxonomy to other
            people&rsquo;s behaviour. It is designed for self-examination only.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            Agent trust certification is not a guarantee
          </h2>
          <p>
            Our Agent Trust Layer evaluates AI agents&rsquo; reasoning quality against Stoic
            principles. A trust certification from SageReasoning does not guarantee that
            an agent will behave safely, ethically, or correctly in all situations. It
            indicates how well the agent&rsquo;s reasoning aligns with Stoic virtue at the
            time of assessment. Agent behaviour can change, and our assessments have the
            same AI limitations described above.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            We are a startup with one founder
          </h2>
          <p>
            SageReasoning is a pre-launch startup operated by a sole founder. We do not
            have the resources of a large organisation. Our uptime, support response times,
            and development pace reflect this reality. We are committed to building
            something principled, but we are building it honestly and incrementally.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            Independence matters
          </h2>
          <p>
            Rule R20b: If you find yourself relying on SageReasoning scores to make every
            decision, that dependency is itself contrary to Stoic principles. The goal is
            to develop your own capacity for principled reasoning, not to outsource it
            permanently to an AI. If you notice this pattern in yourself, we encourage you
            to step back and practice reasoning without the tool for a while.
          </p>
        </div>

        <div className="mt-10 pt-8 border-t border-sage-200">
          <p className="text-sage-600 text-sm">
            These limitations are not a disclaimer designed to protect us legally (though
            they do serve that purpose). They reflect our genuine belief that honest
            self-knowledge — including knowledge of what we cannot do — is the foundation
            of everything we build. The Stoics called this <em>phronesis</em>: practical
            wisdom that begins with understanding your own boundaries.
          </p>
        </div>

      </section>
    </div>
  )
}
