/**
 * /welcome — First-run orientation for newly signed-up practitioners
 *
 * Build item A18a (staging plan §A18): "Sagereasoning.com first-run experience
 * designed + built (U1)." Human-practitioner first-run only this session.
 *
 * Purpose: the bridge between "I just made an account" and "I know what to do
 * here." Shown once right after the baseline result (the baseline result CTA
 * now hands off here), and reachable any time from the nav account menu and the
 * footer.
 *
 * Honest positioning per R19 (R19c limitations / R19d mirror principle): we
 * frame the tool as a mirror for the practitioner's OWN reasoning, AI-generated,
 * a companion rather than advice — and link to /limitations, /transparency, and
 * /accessibility rather than overclaiming. Static page; no auth logic; matches
 * the /accessibility + /limitations page conventions.
 */

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Getting Started — SageReasoning',
  description:
    'A short orientation for new practitioners: what SageReasoning is for, a few things worth trying first, how to read your results, and what to expect honestly.',
}

const FIRST_STEPS = [
  {
    title: 'Take your baseline',
    href: '/baseline',
    body:
      'A short set of questions that calibrates where your practice is starting from. It is not a grade — it is a starting point you can build on.',
    cta: 'Start the baseline',
  },
  {
    title: 'Score an action',
    href: '/score',
    body:
      'The everyday tool. Describe something you did, or plan to do, and receive a Stoic reading of your reasoning along with a path for growth.',
    cta: 'Score an action',
  },
  {
    title: 'Keep a journal',
    href: '/journal',
    body:
      'A quiet place to record what you noticed and return to it later. Patterns become visible over time in a way they rarely do in the moment.',
    cta: 'Open the journal',
  },
  {
    title: 'Meet your private mentor',
    href: '/private-mentor',
    body:
      'A reflective companion for deeper examination — for working through a decision or a reaction by following your own reasoning more carefully.',
    cta: 'Meet the mentor',
  },
]

const MORE_TO_EXPLORE = [
  { label: 'Ethical scenarios', href: '/scenarios' },
  { label: 'Preparing for Adversity (premeditatio)', href: '/premeditatio' },
  { label: 'The community map', href: '/community' },
  { label: 'How the method works', href: '/methodology' },
]

export default function WelcomePage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 font-body text-sage-800">

      {/* Header */}
      <div className="mb-12">
        <h1 className="font-display text-3xl font-medium text-sage-900 mb-2">
          Welcome to SageReasoning
        </h1>
        <p className="font-display text-lg italic text-sage-600 mb-4">Flourish together</p>
        <p className="text-sage-700 leading-relaxed">
          You now have a place to examine your own judgments, grow in character, and
          practise reasoning a little more like the Stoic sage. This page is a short
          orientation: what the tool is for, a few things worth trying first, and how to
          read what you get back. You can return here any time from the account menu or
          the footer.
        </p>
      </div>

      <section className="space-y-12 leading-relaxed">

        {/* A companion for your reasoning */}
        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            A mirror, not a verdict
          </h2>
          <p>
            SageReasoning holds up a mirror to your <em>own</em> reasoning. When you score
            an action or reflect with the mentor, the aim is to help you see your judgments,
            passions, and intentions more clearly — not to hand down a verdict on you as a
            person. The reflections are generated by an AI model and are a companion to your
            thinking, not professional advice and not the last word. If something it says
            does not ring true, trust your own examination over the output. For the fuller
            picture of what this tool can and cannot do, see our{' '}
            <a href="/limitations" className="text-sage-600 underline hover:text-sage-800">
              limitations page
            </a>
            .
          </p>
        </div>

        {/* Where to start */}
        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-5">
            Where to start
          </h2>
          <p className="mb-6 text-sage-700">
            There is no single right order. If you are not sure, scoring an action is the
            most direct way to feel what SageReasoning does.
          </p>
          <div className="grid sm:grid-cols-2 gap-5">
            {FIRST_STEPS.map((step) => (
              <div
                key={step.href}
                className="bg-white/60 border border-sage-200 rounded-lg p-6 flex flex-col"
              >
                <h3 className="font-display text-lg font-semibold text-sage-800 mb-2">
                  {step.title}
                </h3>
                <p className="text-sm text-sage-700 leading-relaxed mb-4 flex-1">
                  {step.body}
                </p>
                <a
                  href={step.href}
                  className="inline-block self-start px-4 py-2 bg-sage-400 text-white font-display text-sm rounded hover:bg-sage-500 transition-colors"
                >
                  {step.cta}
                </a>
              </div>
            ))}
          </div>
        </div>

        {/* How to read your results */}
        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            How to read your results
          </h2>
          <p>
            Results are <strong>qualitative, not a score out of ten</strong>. Your reasoning
            is described by how closely it approaches the ideal of the perfect Stoic sage —
            from <em>reflexive</em> (little self-examination) through to <em>sage-like</em>{' '}
            (rare philosophical depth). The point of the levels is direction, not ranking:
            they show where to look next. Any passions the tool names — frustration, craving
            for recognition, anxiety — are offered as <strong>diagnostic, not punitive</strong>.
            Naming them is how Stoic practice begins to loosen their grip. If you want the
            reasoning behind all of this, the{' '}
            <a href="/methodology" className="text-sage-600 underline hover:text-sage-800">
              methodology page
            </a>{' '}
            sets out the full four-stage approach.
          </p>
        </div>

        {/* More to explore */}
        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            More to explore
          </h2>
          <p className="mb-4 text-sage-700">
            When you are ready to go further, these are worth a look:
          </p>
          <ul className="space-y-2">
            {MORE_TO_EXPLORE.map((item) => (
              <li key={item.href}>
                <a
                  href={item.href}
                  className="text-sage-600 underline hover:text-sage-800"
                >
                  {item.label}
                </a>
              </li>
            ))}
          </ul>
        </div>

        {/* Honest expectations */}
        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">
            What to expect — honestly
          </h2>
          <p>
            SageReasoning is a pre-launch tool built by a single founder, and we would
            rather be plain with you than overclaim. The reflections are AI-generated and
            can vary in quality. This is <strong>not a crisis or mental-health service</strong>;
            if you are struggling, please reach out to a qualified professional or a local
            support line. You can read how we handle your data on our{' '}
            <a href="/privacy" className="text-sage-600 underline hover:text-sage-800">
              privacy
            </a>{' '}
            and{' '}
            <a href="/transparency" className="text-sage-600 underline hover:text-sage-800">
              AI transparency
            </a>{' '}
            pages, and how we approach{' '}
            <a href="/accessibility" className="text-sage-600 underline hover:text-sage-800">
              accessibility
            </a>{' '}
            here. If anything is unclear or could be better, tell us at{' '}
            <a
              href="mailto:support@sagereasoning.com"
              className="text-sage-600 underline hover:text-sage-800"
            >
              support@sagereasoning.com
            </a>
            .
          </p>
        </div>

        {/* CTA */}
        <div className="mt-4 pt-8 border-t border-sage-200 text-center space-y-4">
          <p className="font-display text-xl text-sage-800">Begin your path toward the Sage</p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <a
              href="/score"
              className="px-8 py-3 bg-sage-400 text-white font-display text-lg rounded hover:bg-sage-500 transition-colors"
            >
              Score your first action
            </a>
            <a
              href="/dashboard"
              className="px-8 py-3 border border-sage-400 text-sage-700 font-display text-lg rounded hover:bg-sage-100 transition-colors"
            >
              Go to your dashboard
            </a>
          </div>
        </div>

      </section>
    </div>
  )
}
