import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — SageReasoning',
  description: 'Terms of Service for SageReasoning.com',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 font-body text-sage-800">
      {/* ── LEGAL REVIEW PLACEHOLDER ─────────────────────────────────────────── */}
      {/* TODO (Priority 9 — Phase 1): This page contains a draft framework only.
          Before accepting any revenue, have an Australian technology lawyer review
          and finalise this document. Estimated cost: $800–$2,000.
          Governing law: Queensland / Australia. */}
      {/* ─────────────────────────────────────────────────────────────────────── */}

      <div className="mb-10">
        <h1 className="font-display text-3xl font-medium text-sage-900 mb-2">Terms of Service</h1>
        <p className="text-sage-600 text-sm italic">
          Last updated: March 2026 &mdash; Draft pending legal review
        </p>
        <div className="mt-4 px-4 py-3 bg-amber-50 border border-amber-200 rounded text-amber-800 text-sm">
          <strong>Draft notice:</strong> These terms are a working draft. A qualified Australian lawyer
          is reviewing them before they take full legal effect. By using this site you acknowledge
          this notice.
        </div>
      </div>

      <section className="space-y-8 leading-relaxed">

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">1. About SageReasoning</h2>
          <p>
            SageReasoning (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is an online platform that provides Stoic
            philosophy-based reasoning tools for individuals and AI agents. The service is operated
            from Australia and is governed by Australian law.
          </p>
          <p className="mt-3">
            By accessing or using sagereasoning.com (&ldquo;the Site&rdquo;) you agree to be bound by these Terms.
            If you do not agree, please do not use the Site.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">2. What SageReasoning Is Not</h2>
          <p>
            SageReasoning provides AI-generated philosophical perspectives based on Stoic virtue ethics.
            Our scores, reasoning, and content are generated by artificial intelligence and are intended
            for personal reflection and educational purposes only.
          </p>
          <p className="mt-3 font-medium">SageReasoning is not:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>A licensed mental health service, counselling service, or therapy provider</li>
            <li>A legal, financial, medical, or professional advice service</li>
            <li>A certified assessment, qualification, or accreditation</li>
            <li>A substitute for professional judgement in any domain</li>
          </ul>
          <p className="mt-3">
            If you are experiencing a mental health crisis, please contact{' '}
            <strong>Lifeline on 13 11 14</strong> or your local emergency service.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">3. AI-Generated Content</h2>
          <p>
            All scores, reasoning, and recommendations generated by this Site are produced by
            AI (specifically, Anthropic&rsquo;s Claude). AI-generated content may contain errors,
            inaccuracies, or outputs that do not reflect accurate Stoic philosophy. You acknowledge that:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>AI outputs are not infallible and should be critically evaluated</li>
            <li>Scores are one perspective, not a definitive assessment of your character or decisions</li>
            <li>You should apply your own judgement before acting on any AI-generated output</li>
          </ul>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">4. Your Account</h2>
          <p>
            To access personalised features you must create an account. You are responsible for
            keeping your credentials secure. You must provide accurate information and must not
            impersonate another person or create accounts on behalf of others.
          </p>
          <p className="mt-3">
            We reserve the right to suspend accounts that violate these Terms or that are used
            for harmful, fraudulent, or abusive purposes.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">5. Acceptable Use</h2>
          <p>You agree not to use SageReasoning to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>Generate harmful, hateful, threatening, or illegal content</li>
            <li>Attempt to circumvent our security or rate-limiting systems</li>
            <li>Scrape or systematically extract content or data in bulk without permission</li>
            <li>Use our outputs as the sole basis for decisions that significantly affect other people</li>
            <li>Misrepresent AI-generated scores as certified or authoritative assessments</li>
          </ul>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">6. Intellectual Property</h2>
          <p>
            The Stoic Brain data (virtue definitions, scoring framework, and structured philosophical
            compilation) is published under the{' '}
            <strong>SageReasoning Proprietary Licence</strong>. A conceptual overview is freely available
            for evaluation; detailed scoring weights and formulas are provided through the API.
            The website design, code, journal curriculum, and original written content are owned by
            SageReasoning and may not be reproduced without permission. Use of the Stoic Brain data
            to build competing scoring services is prohibited. See the{' '}
            <a href="https://github.com/quartermileclint/sagereasoning/blob/main/LICENSE" className="text-sage-600 underline hover:text-sage-800">full licence</a> for terms.
          </p>
          <p className="mt-3">
            AI-generated scores and reasoning produced on your behalf are not protected by copyright
            (as AI-generated content has no human author under Australian law) and may be used freely
            by you.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by Australian Consumer Law, SageReasoning&rsquo;s liability
            for any loss or damage arising from your use of the Site is limited to the amount you
            paid us in the 12 months prior to the event giving rise to the claim (or $100 if nothing
            was paid).
          </p>
          <p className="mt-3">
            We do not exclude liability for personal injury or death caused by our negligence, or
            for any liability that cannot be excluded under Australian Consumer Law.
          </p>
          {/* TODO: Have a lawyer verify this limitation clause is enforceable under
              the Australian Consumer Law and that consumer guarantees are properly preserved. */}
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">8. Privacy</h2>
          <p>
            Our collection and use of your personal information is governed by our{' '}
            <a href="/privacy" className="text-sage-600 underline hover:text-sage-800">Privacy Policy</a>,
            which forms part of these Terms.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">9. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify registered users of material
            changes by email. Continued use of the Site after notification constitutes acceptance
            of the updated Terms.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">10. Governing Law</h2>
          <p>
            These Terms are governed by the laws of Queensland, Australia. Any disputes will be
            subject to the non-exclusive jurisdiction of the courts of Queensland.
          </p>
          {/* TODO: Lawyer to confirm jurisdiction clause and preferred dispute resolution mechanism. */}
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">11. Contact</h2>
          <p>
            Questions about these Terms may be directed to:{' '}
            {/* TODO: Add dedicated legal/support email address */}
            <span className="text-sage-600 font-mono">support@sagereasoning.com</span>
          </p>
        </div>

      </section>
    </div>
  )
}
