{/*
 * @compliance
 * compliance_version: CR-2026-Q2-v1
 * last_regulatory_review: 2026-04-04
 * applicable_jurisdictions: [AU, EU, US]
 * regulatory_references: [CR-001, CR-002, CR-005, CR-006, CR-009, CR-010, CR-014]
 * review_cycle: quarterly
 * owner: legal-counsel
 * next_review_due: 2026-07-06
 * change_trigger: [EU AI Act classification guidance, AU Privacy Act reform, ACCC AI enforcement action]
 * deprecation_flag: false
 */}
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — SageReasoning',
  description: 'Terms of Service for SageReasoning.com',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 font-body text-sage-800">
      {/* ── LEGAL REVIEW PLACEHOLDER ─────────────────────────────────────────── */}
      {/* TODO (Priority 9 — Phase 1): This page contains a draft framework only.
          Before accepting any revenue, have an Australian technology lawyer review
          and finalise this document. Estimated cost: $800–$2,000.
          Governing law: Queensland / Australia. */}
      {/* ─────────────────────────────────────────────────────────────────────── */}

      <div className="mb-10">
        <h1 className="font-display text-3xl font-medium text-sage-900 mb-2">Terms of Service</h1>
        <p className="text-sage-600 text-sm italic">
          Last updated: March 2026 &mdash; Draft pending legal review
        </p>
        <div className="mt-4 px-4 py-3 bg-amber-50 border border-amber-200 rounded text-amber-800 text-sm">
          <strong>Draft notice:</strong> These terms are a working draft. A qualified Australian lawyer
          is reviewing them before they take full legal effect. By using this site you acknowledge
          this notice.
        </div>
      </div>

      <section className="space-y-8 leading-relaxed">

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">1. About SageReasoning</h2>
          <p>
            SageReasoning (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is an online platform that provides a Stoic
            philosophy-based reasoning engine (sage-reason) and derived evaluation tools for individuals,
            AI agents, and embedding platforms. The service is operated from Australia and is governed
            by Australian law.
          </p>
          <p className="mt-3">
            By accessing or using sagereasoning.com (&ldquo;the Site&rdquo;) you agree to be bound by these Terms.
            If you do not agree, please do not use the Site.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">2. What SageReasoning Is Not</h2>
          <p>
            SageReasoning provides AI-generated philosophical perspectives based on Stoic virtue ethics.
            Our scores, reasoning, and content are generated by artificial intelligence and are intended
            for personal reflection and educational purposes only.
          </p>
          <p className="mt-3 font-medium">SageReasoning is not:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>A licensed mental health service, counselling service, or therapy provider</li>
            <li>A legal, financial, medical, or professional advice service</li>
            <li>A certified assessment, qualification, or accreditation</li>
            <li>A substitute for professional judgement in any domain</li>
          </ul>
          <p className="mt-3">
            If you are experiencing a mental health crisis, please contact{' '}
            <strong>Lifeline on 13 11 14</strong> or your local emergency service.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">3. AI-Generated Content</h2>
          <p>
            All scores, reasoning, and recommendations generated by this Site are produced by
            AI (specifically, Anthropic&rsquo;s Claude). AI-generated content may contain errors,
            inaccuracies, or outputs that do not reflect accurate Stoic philosophy. You acknowledge that:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>AI outputs are not infallible and should be critically evaluated</li>
            <li>Scores are one perspective, not a definitive assessment of your character or decisions</li>
            <li>You should apply your own judgement before acting on any AI-generated output</li>
          </ul>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">4. Your Account</h2>
          <p>
            To access personalised features you must create an account. You are responsible for
            keeping your credentials secure. You must provide accurate information and must not
            impersonate another person or create accounts on behalf of others.
          </p>
          <p className="mt-3">
            We reserve the right to suspend accounts that violate these Terms or that are used
            for harmful, fraudulent, or abusive purposes.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">5. Acceptable Use</h2>
          <p>You agree not to use SageReasoning to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>Generate harmful, hateful, threatening, or illegal content</li>
            <li>Attempt to circumvent our security or rate-limiting systems</li>
            <li>Scrape or systematically extract content or data in bulk without permission</li>
            <li>Use our outputs as the sole basis for decisions that significantly affect other people</li>
            <li>Misrepresent AI-generated scores as certified or authoritative assessments</li>
            <li>Present sage-reason output as mental health advice, therapeutic insight, mood assessment, or clinical feedback</li>
            <li>Use sage-reason within hiring, employment screening, promotion, or any HR assessment process</li>
            <li>Claim that sage-reason output constitutes legal, regulatory, or financial compliance certification</li>
          </ul>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">6. Intellectual Property</h2>
          <p>
            The Stoic Brain data (reasoning framework, evaluation sequence design, passions diagnostic,
            proximity scale, and structured philosophical compilation) is published under the{' '}
            <strong>SageReasoning Proprietary Licence</strong>. A conceptual overview is freely available
            for evaluation; detailed evaluation logic is provided through the API.
          </p>
          <p className="mt-3">
            The website design, code, journal curriculum, original written content, and all{' '}
            <strong>original sage skills</strong> (sage-premortem, sage-negotiate, sage-invest,
            sage-hire, sage-pivot, sage-retro, sage-align, sage-prioritise, sage-resolve,
            sage-identity, sage-coach, sage-govern, sage-clinical, sage-compliance, sage-moderate,
            sage-educate) are owned by SageReasoning and may not be reproduced without permission.
          </p>
          <p className="mt-3">
            <strong>Sage skill wrapper</strong> code (the open-source checkpoint logic that calls
            sage-guard and sage-score around existing skills) is distributed under a permissive
            licence. However, the SageReasoning API endpoints that wrappers invoke remain proprietary.
            The <strong>sage-</strong> naming convention and associated skill descriptions are
            trademarks of SageReasoning.
          </p>
          <p className="mt-3">
            Use of the Stoic Brain data to build competing reasoning evaluation services is
            prohibited. See the{' '}
            <a href="https://github.com/quartermileclint/sagereasoning/blob/main/LICENSE" className="text-sage-600 underline hover:text-sage-800">full licence</a> for terms.
          </p>
          <p className="mt-3">
            AI-generated reasoning evaluations produced on your behalf are not protected by copyright
            (as AI-generated content has no human author under Australian law) and may be used freely
            by you.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">7. Marketplace</h2>
          <p>
            SageReasoning operates a marketplace where original sage skills are available for
            purchase. By using the marketplace (via the website or agent-facing API endpoints)
            you agree to the following:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1 text-sage-700">
            <li>
              <strong>Skill acquisition</strong> grants a non-exclusive, non-transferable licence
              to invoke that skill via the SageReasoning API. Skills are not downloaded; they
              execute server-side.
            </li>
            <li>
              <strong>Pricing</strong> is displayed per-call on the marketplace. SageReasoning
              reserves the right to adjust pricing with 30 days notice to active subscribers.
            </li>
            <li>
              <strong>Availability:</strong> SageReasoning may add, modify, or retire skills
              from the marketplace. Acquired skills remain accessible for the duration of your
              active subscription.
            </li>
            <li>
              <strong>Agent-facing API:</strong> The <code>/api/marketplace</code> endpoints are
              subject to the same terms as human marketplace access.
            </li>
          </ul>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">8. Sage Skill Wrappers</h2>
          <p>
            Sage skill wrappers are open-source code that adds pre-action and post-action
            reasoning checkpoints around existing skills. The wrapper code is free; the API
            calls within the wrapper (sage-guard, sage-score, sage-iterate) are metered services
            counted against your monthly API allowance.
          </p>
          <p className="mt-3">
            A single sage-wrapped skill invocation may consume 2&ndash;3 API calls. Usage through
            wrappers is subject to the same rate limits, pricing, and terms as direct API access.
          </p>
          <p className="mt-3">
            SageReasoning evaluates reasoning quality only. The output of the underlying wrapped
            skill is outside SageReasoning&rsquo;s control and responsibility.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">9. Free Tier</h2>
          <p>
            Free API access provides 100 calls per month with rate limiting. The free tier
            provides full evaluation output on all endpoints &mdash; the distinction between
            free and paid is volume, not capability. Free tier access may be modified or
            discontinued with 30 days notice.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">10. Embedding Platforms</h2>
          <p>
            If you embed sage-reason within your own product (as an API integration), you are
            responsible for ensuring that your product&rsquo;s use of sage-reason complies with
            these Terms, including the Acceptable Use restrictions in Section 5.
          </p>
          <p className="mt-3">
            You must not represent sage-reason output as your own proprietary analysis without
            attribution to SageReasoning. You must pass through the standard disclaimer
            (&ldquo;Ancient reasoning, modern application. Does not consider legal, medical,
            financial, or personal obligations.&rdquo;) to your end users in a visible location.
          </p>
          <p className="mt-3">
            sage-reason evaluates the quality of decision-making reasoning, not the subject matter
            of the decisions being made. Embedding platforms must not frame sage-reason output in a
            way that implies assessment of the subject matter itself.
          </p>
          <p className="mt-3">
            sage-reason calls made by wrappers, skills, or embedding platform integrations are all
            counted against the same monthly API allowance and subject to the same rate limits.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">11. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by Australian Consumer Law, SageReasoning&rsquo;s liability
            for any loss or damage arising from your use of the Site is limited to the amount you
            paid us in the 12 months prior to the event giving rise to the claim (or $100 if nothing
            was paid).
          </p>
          <p className="mt-3">
            We do not exclude liability for personal injury or death caused by our negligence, or
            for any liability that cannot be excluded under Australian Consumer Law.
          </p>
          {/* TODO: Have a lawyer verify this limitation clause is enforceable under
              the Australian Consumer Law and that consumer guarantees are properly preserved. */}
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">12. Privacy</h2>
          <p>
            Our collection and use of your personal information is governed by our{' '}
            <a href="/privacy" className="text-sage-600 underline hover:text-sage-800">Privacy Policy</a>,
            which forms part of these Terms.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">13. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify registered users of material
            changes by email. Continued use of the Site after notification constitutes acceptance
            of the updated Terms.
          </p>
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">14. Governing Law</h2>
          <p>
            These Terms are governed by the laws of Queensland, Australia. Any disputes will be
            subject to the non-exclusive jurisdiction of the courts of Queensland.
          </p>
          {/* TODO: Lawyer to confirm jurisdiction clause and preferred dispute resolution mechanism. */}
        </div>

        <div>
          <h2 className="font-display text-xl font-semibold text-sage-800 mb-3">15. Contact</h2>
          <p>
            Questions about these Terms may be directed to:{' '}
            {/* TODO: Add dedicated legal/support email address */}
            <span className="text-sage-600 font-mono">support@sagereasoning.com</span>
          </p>
        </div>

      </section>
    </div>
  )
}
