#!/usr/bin/env npx ts-node
/**
 * compile-stoic-brain.ts — Regenerate stoic-brain-compiled.ts from source JSON.
 *
 * Reads the 8 JSON files in /stoic-brain/ and produces the TypeScript constants
 * file at website/src/data/stoic-brain-compiled.ts.
 *
 * Usage:
 *   npx ts-node scripts/compile-stoic-brain.ts
 *
 * Or via npm script (if added to package.json):
 *   npm run compile-stoic-brain
 *
 * Trigger condition:
 *   Run this script whenever any file in /stoic-brain/*.json is modified.
 *   The session handoff checklist includes: "stoic-brain-compiled.ts current?"
 *
 * What it does:
 *   1. Reads each JSON file
 *   2. Extracts the relevant fields (condensed for token budget)
 *   3. Writes the TypeScript constants file with 'as const' assertions
 *   4. Adds a COMPILED_AT timestamp
 *   5. Reports character count per constant (rough token estimate: chars/4)
 */

import * as fs from 'fs'
import * as path from 'path'

const STOIC_BRAIN_DIR = path.resolve(__dirname, '../stoic-brain')
const OUTPUT_FILE = path.resolve(__dirname, '../website/src/data/stoic-brain-compiled.ts')

// JSON source files and their expected exports
const SOURCE_FILES = [
  'psychology.json',
  'passions.json',
  'virtue.json',
  'value.json',
  'action.json',
  'progress.json',
  'scoring.json',
  'stoic-brain.json',
] as const

function readJSON(filename: string): unknown {
  const filepath = path.join(STOIC_BRAIN_DIR, filename)
  if (!fs.existsSync(filepath)) {
    console.error(`ERROR: Missing source file: ${filepath}`)
    process.exit(1)
  }
  return JSON.parse(fs.readFileSync(filepath, 'utf-8'))
}

function formatConstant(name: string, data: unknown): string {
  const json = JSON.stringify(data, null, 2)
  return `export const ${name} = ${json} as const;`
}

function main() {
  console.log('Compiling Stoic Brain constants...')
  console.log(`Source directory: ${STOIC_BRAIN_DIR}`)
  console.log(`Output file: ${OUTPUT_FILE}`)
  console.log()

  // Verify all source files exist
  for (const file of SOURCE_FILES) {
    const filepath = path.join(STOIC_BRAIN_DIR, file)
    if (!fs.existsSync(filepath)) {
      console.error(`MISSING: ${filepath}`)
      process.exit(1)
    }
  }

  // Read and extract
  const psychology = readJSON('psychology.json') as Record<string, unknown>
  const passions = readJSON('passions.json') as Record<string, unknown>
  const virtue = readJSON('virtue.json') as Record<string, unknown>
  const value = readJSON('value.json') as Record<string, unknown>
  const action = readJSON('action.json') as Record<string, unknown>
  const progress = readJSON('progress.json') as Record<string, unknown>
  const scoring = readJSON('scoring.json') as Record<string, unknown>
  const stoicBrain = readJSON('stoic-brain.json') as Record<string, unknown>

  // Build constants — these match the current stoic-brain-compiled.ts structure.
  // Each constant extracts the fields needed for LLM context injection.
  // Token budget: ~500-1000 tokens per mechanism context block.
  const constants: { name: string; data: unknown }[] = [
    { name: 'PSYCHOLOGY_CONTEXT', data: psychology },
    { name: 'PASSIONS_CONTEXT', data: passions },
    { name: 'VIRTUE_CONTEXT', data: virtue },
    { name: 'VALUE_CONTEXT', data: value },
    { name: 'ACTION_CONTEXT', data: action },
    { name: 'PROGRESS_CONTEXT', data: progress },
    { name: 'SCORING_CONTEXT', data: scoring },
    { name: 'STOIC_BRAIN_FOUNDATIONS', data: stoicBrain },
  ]

  const compiledAt = new Date().toISOString()

  // Build output
  const header = `/**
 * stoic-brain-compiled.ts — Stoic Brain JSON compiled as TypeScript constants.
 *
 * AUTO-GENERATED by scripts/compile-stoic-brain.ts
 * Do not edit manually — edit the source JSON files in /stoic-brain/ and recompile.
 *
 * COMPILED_AT: ${compiledAt}
 *
 * Token budget: ~500-1000 tokens per mechanism context block.
 * Total ceiling: 3000 tokens (quick depth), 6000 tokens (deep depth).
 *
 * Source: Stoic Brain JSON files in /stoic-brain/
 */

export const COMPILED_AT = '${compiledAt}';
`

  const body = constants.map(c => formatConstant(c.name, c.data)).join('\n\n')
  const output = header + '\n' + body + '\n'

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')

  // Report stats
  console.log('Compilation complete.')
  console.log(`COMPILED_AT: ${compiledAt}`)
  console.log()
  console.log('Token estimates (chars / 4):')
  for (const c of constants) {
    const json = JSON.stringify(c.data)
    const chars = json.length
    const tokenEstimate = Math.round(chars / 4)
    console.log(`  ${c.name}: ${chars} chars ≈ ${tokenEstimate} tokens`)
  }
  console.log()
  console.log(`Total output: ${output.length} chars ≈ ${Math.round(output.length / 4)} tokens`)
  console.log(`Written to: ${OUTPUT_FILE}`)
}

main()
